name: CI/CD to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name zeyanregistry
      - name: Build Image
        run: docker build -t zeyanregistry.azurecr.io/myapp:latest .

      - name: Push Image
        run: docker push zeyanregistry.azurecr.io/myapp:latest

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name my-container-app \
            --resource-group rg-dev-mumbai-01 \
            --image zeyanregistry.azurecr.io/myapp:latest